// FICHIER GÉNÉRÉ — ne pas éditer à la main.
// Régénérer avec le script gen-icons.mjs après avoir ajouté une icône.
//
// Ne contient QUE les 62 icônes réellement utilisées dans les templates,
// au lieu des ~7000 de la police complète. Les alias internes de Vuetify
// (flèches de listes, coches, navigation du calendrier) viennent de
// 'vuetify/iconsets/mdi-svg' et sont déjà des chemins SVG.
import {
  mdiAccount,
  mdiAccountGroup,
  mdiAccountMultipleOutline,
  mdiAccountMusic,
  mdiAccountSchool,
  mdiAirplane,
  mdiArrowLeft,
  mdiArrowRight,
  mdiBookMusic,
  mdiCalendarMonth,
  mdiCalendarRefresh,
  mdiCalendarStar,
  mdiCalendarToday,
  mdiChartBar,
  mdiCheck,
  mdiCheckCircle,
  mdiCheckCircleOutline,
  mdiChevronLeft,
  mdiChevronRight,
  mdiCircle,
  mdiClipboardCheckOutline,
  mdiClose,
  mdiCloseCircle,
  mdiCloseCircleOutline,
  mdiCloseOctagonOutline,
  mdiCookie,
  mdiCrown,
  mdiDelete,
  mdiDeleteForever,
  mdiDotsHorizontal,
  mdiEraser,
  mdiEye,
  mdiEyeOff,
  mdiFileCheckOutline,
  mdiFileDocumentMultipleOutline,
  mdiFilePdfBox,
  mdiFlagVariantOutline,
  mdiFormatListBulleted,
  mdiGoogleClassroom,
  mdiHelpCircleOutline,
  mdiHome,
  mdiInformationOutline,
  mdiLock,
  mdiLogout,
  mdiMessageText,
  mdiMinus,
  mdiMinusCircleOutline,
  mdiNotePlusOutline,
  mdiNoteText,
  mdiNoteTextOutline,
  mdiOpenInNew,
  mdiPencil,
  mdiPhone,
  mdiPlus,
  mdiPlusCircleOutline,
  mdiRefresh,
  mdiRestore,
  mdiScaleBalance,
  mdiSend,
  mdiShieldAccount,
  mdiShieldLock,
  mdiSwapHorizontal,
} from '@mdi/js'

// Table nom Material Design -> chemin SVG
export const APP_ICONS = {
  'mdi-account': mdiAccount,
  'mdi-account-group': mdiAccountGroup,
  'mdi-account-multiple-outline': mdiAccountMultipleOutline,
  'mdi-account-music': mdiAccountMusic,
  'mdi-account-school': mdiAccountSchool,
  'mdi-airplane': mdiAirplane,
  'mdi-arrow-left': mdiArrowLeft,
  'mdi-arrow-right': mdiArrowRight,
  'mdi-book-music': mdiBookMusic,
  'mdi-calendar-month': mdiCalendarMonth,
  'mdi-calendar-refresh': mdiCalendarRefresh,
  'mdi-calendar-star': mdiCalendarStar,
  'mdi-calendar-today': mdiCalendarToday,
  'mdi-chart-bar': mdiChartBar,
  'mdi-check': mdiCheck,
  'mdi-check-circle': mdiCheckCircle,
  'mdi-check-circle-outline': mdiCheckCircleOutline,
  'mdi-chevron-left': mdiChevronLeft,
  'mdi-chevron-right': mdiChevronRight,
  'mdi-circle': mdiCircle,
  'mdi-clipboard-check-outline': mdiClipboardCheckOutline,
  'mdi-close': mdiClose,
  'mdi-close-circle': mdiCloseCircle,
  'mdi-close-circle-outline': mdiCloseCircleOutline,
  'mdi-close-octagon-outline': mdiCloseOctagonOutline,
  'mdi-cookie': mdiCookie,
  'mdi-crown': mdiCrown,
  'mdi-delete': mdiDelete,
  'mdi-delete-forever': mdiDeleteForever,
  'mdi-dots-horizontal': mdiDotsHorizontal,
  'mdi-eraser': mdiEraser,
  'mdi-eye': mdiEye,
  'mdi-eye-off': mdiEyeOff,
  'mdi-file-check-outline': mdiFileCheckOutline,
  'mdi-file-document-multiple-outline': mdiFileDocumentMultipleOutline,
  'mdi-file-pdf-box': mdiFilePdfBox,
  'mdi-flag-variant-outline': mdiFlagVariantOutline,
  'mdi-format-list-bulleted': mdiFormatListBulleted,
  'mdi-google-classroom': mdiGoogleClassroom,
  'mdi-help-circle-outline': mdiHelpCircleOutline,
  'mdi-home': mdiHome,
  'mdi-information-outline': mdiInformationOutline,
  'mdi-lock': mdiLock,
  'mdi-logout': mdiLogout,
  'mdi-message-text': mdiMessageText,
  'mdi-minus': mdiMinus,
  'mdi-minus-circle-outline': mdiMinusCircleOutline,
  'mdi-note-plus-outline': mdiNotePlusOutline,
  'mdi-note-text': mdiNoteText,
  'mdi-note-text-outline': mdiNoteTextOutline,
  'mdi-open-in-new': mdiOpenInNew,
  'mdi-pencil': mdiPencil,
  'mdi-phone': mdiPhone,
  'mdi-plus': mdiPlus,
  'mdi-plus-circle-outline': mdiPlusCircleOutline,
  'mdi-refresh': mdiRefresh,
  'mdi-restore': mdiRestore,
  'mdi-scale-balance': mdiScaleBalance,
  'mdi-send': mdiSend,
  'mdi-shield-account': mdiShieldAccount,
  'mdi-shield-lock': mdiShieldLock,
  'mdi-swap-horizontal': mdiSwapHorizontal,
}
