name: Deploy Front to 1hebergement

on:
  push:
    branches: [ main ]
    paths:
      - "**/*"
      - "!README.md"

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          # 👇 le lockfile est à la racine du dépôt
          cache-dependency-path: "package-lock.json"

      - name: Install deps
        run: npm ci --no-audit --no-fund || npm i --legacy-peer-deps

      - name: Inject prod env
        run: echo "VITE_API_URL=${{ secrets.VITE_API_URL }}" > .env.production

      - name: Build
        run: npm run build

      - name: Preflight check
        run: |
          echo "FTP host: ${{ secrets.FTP_HOST }}"
          ls -lah dist || true

      # --- Déploiement : FTPS d'abord ---
      - name: Deploy via FTPS
        id: deploy_ftps
        continue-on-error: true
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          protocol: ftps
          port: 21
          local-dir: dist/     # 👈 le build Vite sort ici, à la racine
          server-dir: /        # 👈 ton compte FTP ouvre /home/.../public_html
          log-level: verbose

      # --- Si FTPS échoue, on retente en FTP simple ---
      - name: Retry with plain FTP
        if: steps.deploy_ftps.outcome == 'failure'
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          protocol: ftp
          port: 21
          local-dir: dist/
          server-dir: /
          log-level: verbose
