name: Deploy Front to 1hebergement

on:
  push:
    branches: [ main ]
    paths:
      - "pointage-web/**"
      - ".github/workflows/deploy-frontend.yml"

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: pointage-web

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: "pointage-web/package-lock.json"

      - name: Install deps
        run: npm ci

      - name: Inject prod env
        # crée .env.production au moment du build
        run: echo "VITE_API_URL=${{ secrets.VITE_API_URL }}" > .env.production

      - name: Build
        run: npm run build

      - name: Deploy via FTP (FTPS)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          protocol: ftps          # ← si ça bloque, essaie: ftp
          port: 21
          local-dir: pointage-web/dist/
          server-dir: ./          # ← car l’utilisateur FTP est enfermé dans public_html/
          exclude: |
            **/.git*
            **/.github*
            **/node_modules/**
